//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang quản trị.
        /// </summary>
        internal static string AdminPage {
            get {
                return ResourceManager.GetString("AdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nâng cao.
        /// </summary>
        internal static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có địa danh.
        /// </summary>
        internal static string ChuaCoDiaDanh {
            get {
                return ResourceManager.GetString("ChuaCoDiaDanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng video.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        internal static string Des {
            get {
                return ResourceManager.GetString("Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa có tài khoản.
        /// </summary>
        internal static string donthaveacc {
            get {
                return ResourceManager.GetString("donthaveacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời tiết hiện tại.
        /// </summary>
        internal static string forecast {
            get {
                return ResourceManager.GetString("forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ ẩm.
        /// </summary>
        internal static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa tìm kiếm.
        /// </summary>
        internal static string inputtext {
            get {
                return ResourceManager.GetString("inputtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string intro {
            get {
                return ResourceManager.GetString("intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string introduce {
            get {
                return ResourceManager.GetString("introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video giới thiệu.
        /// </summary>
        internal static string IntroductionVideo {
            get {
                return ResourceManager.GetString("IntroductionVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN KẾT WEBSITE.
        /// </summary>
        internal static string linkto {
            get {
                return ResourceManager.GetString("linkto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách các tour du lịch Điện Biên.
        /// </summary>
        internal static string linktour {
            get {
                return ResourceManager.GetString("linktour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tour.
        /// </summary>
        internal static string Listtour {
            get {
                return ResourceManager.GetString("Listtour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng nhập thành công. Vui lòng &quot;Đăng xuất&quot; để đăng nhập lại.
        /// </summary>
        internal static string Login_Note {
            get {
                return ResourceManager.GetString("Login_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ du lịch.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ du lịch.
        /// </summary>
        internal static string maptour {
            get {
                return ResourceManager.GetString("maptour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoặc.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khác.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện Biên.
        /// </summary>
        internal static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng.
        /// </summary>
        internal static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐƯỢC XEM NHIỀU.
        /// </summary>
        internal static string popularPosts {
            get {
                return ResourceManager.GetString("popularPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour liên quan.
        /// </summary>
        internal static string RelatedTour {
            get {
                return ResourceManager.GetString("RelatedTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string searchAll {
            get {
                return ResourceManager.GetString("searchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn danh mục.
        /// </summary>
        internal static string Searchfor {
            get {
                return ResourceManager.GetString("Searchfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy kết quả nào.
        /// </summary>
        internal static string search_not_found {
            get {
                return ResourceManager.GetString("search_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn lớp bản đồ.
        /// </summary>
        internal static string selectCategory {
            get {
                return ResourceManager.GetString("selectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn lớp bản đồ.
        /// </summary>
        internal static string SelectMapLayer {
            get {
                return ResourceManager.GetString("SelectMapLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các địa điểm chi tiết.
        /// </summary>
        internal static string sub_location {
            get {
                return ResourceManager.GetString("sub_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỖ TRỢ TRỰC TUYẾN.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người hỗ trợ.
        /// </summary>
        internal static string supporters {
            get {
                return ResourceManager.GetString("supporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỆ THỐNG DU LỊCH THÔNG MINH TỪ XA ĐIỆN BIÊN.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to để bình luận.
        /// </summary>
        internal static string tocomment {
            get {
                return ResourceManager.GetString("tocomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour du lịch.
        /// </summary>
        internal static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BẢN ĐỒ DU LỊCH ĐIỆN BIÊN.
        /// </summary>
        internal static string touristmap {
            get {
                return ResourceManager.GetString("touristmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí đi qua.
        /// </summary>
        internal static string touritem {
            get {
                return ResourceManager.GetString("touritem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lượt xem.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời tiết.
        /// </summary>
        internal static string Werther {
            get {
                return ResourceManager.GetString("Werther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tốc độ gió.
        /// </summary>
        internal static string windspeed {
            get {
                return ResourceManager.GetString("windspeed", resourceCulture);
            }
        }
    }
}
