//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public agent()
        {
            this.agent_category_permission = new HashSet<agent_category_permission>();
            this.smt_layer = new HashSet<smt_layer>();
            this.smt_location = new HashSet<smt_location>();
            this.smt_parent_category = new HashSet<smt_parent_category>();
            this.smt_sub_category = new HashSet<smt_sub_category>();
            this.smt_user = new HashSet<smt_user>();
        }
    
        public int agent_id { get; set; }
        public string agent_name { get; set; }
        public string agent_des { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual group group { get; set; }
        public virtual ICollection<agent_category_permission> agent_category_permission { get; set; }
        public virtual ICollection<smt_layer> smt_layer { get; set; }
        public virtual ICollection<smt_location> smt_location { get; set; }
        public virtual ICollection<smt_parent_category> smt_parent_category { get; set; }
        public virtual ICollection<smt_sub_category> smt_sub_category { get; set; }
        public virtual ICollection<smt_user> smt_user { get; set; }
    }
}
