//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smtdbEntities : DbContext
    {
        public smtdbEntities()
            : base("name=smtdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<agent> agents { get; set; }
        public DbSet<agent_category_permission> agent_category_permission { get; set; }
        public DbSet<article> articles { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<smt_comment> smt_comment { get; set; }
        public DbSet<smt_contact> smt_contact { get; set; }
        public DbSet<smt_intro> smt_intro { get; set; }
        public DbSet<smt_layer> smt_layer { get; set; }
        public DbSet<smt_link_tour> smt_link_tour { get; set; }
        public DbSet<smt_location> smt_location { get; set; }
        public DbSet<smt_parent_category> smt_parent_category { get; set; }
        public DbSet<smt_sub_category> smt_sub_category { get; set; }
        public DbSet<smt_support_online> smt_support_online { get; set; }
        public DbSet<smt_user> smt_user { get; set; }
        public DbSet<smt_user_history> smt_user_history { get; set; }
    }
}
