//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smt_parent_category
    {
        public smt_parent_category()
        {
            this.smt_sub_category = new HashSet<smt_sub_category>();
        }
    
        public int parent_category_id { get; set; }
        public string parent_category_name_vi { get; set; }
        public string parent_category_name_en { get; set; }
        public string parent_category_des_vi { get; set; }
        public string parent_category_des_en { get; set; }
        public Nullable<int> parent_category_user_created { get; set; }
        public Nullable<System.DateTime> parent_category_time_created { get; set; }
        public Nullable<int> parent_category_user_modified { get; set; }
        public Nullable<System.DateTime> parent_category_time_modified { get; set; }
        public Nullable<int> parent_agent_id { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual smt_user smt_user { get; set; }
        public virtual ICollection<smt_sub_category> smt_sub_category { get; set; }
    }
}
