//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smt_layer
    {
        public smt_layer()
        {
            this.smt_location = new HashSet<smt_location>();
        }
    
        public int layer_id { get; set; }
        public string layer_name { get; set; }
        public string layer_des_vi { get; set; }
        public string layer_des_en { get; set; }
        public string layer_url { get; set; }
        public Nullable<System.DateTime> layer_time_created { get; set; }
        public Nullable<int> layer_agent_id { get; set; }
        public Nullable<int> layer_user_created { get; set; }
        public string layer_bounding_box { get; set; }
        public string connector { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual smt_user smt_user { get; set; }
        public virtual ICollection<smt_location> smt_location { get; set; }
    }
}
