//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smt_sub_category
    {
        public smt_sub_category()
        {
            this.agent_category_permission = new HashSet<agent_category_permission>();
        }
    
        public int sub_category_id { get; set; }
        public Nullable<int> parent_category_id { get; set; }
        public string sub_category_name_vi { get; set; }
        public string sub_category_name_en { get; set; }
        public string sub_category_des_vi { get; set; }
        public string sub_category_des_en { get; set; }
        public Nullable<int> sub_category_user_created { get; set; }
        public Nullable<System.DateTime> sub_category_time_created { get; set; }
        public Nullable<int> sub_category_user_modified { get; set; }
        public Nullable<System.DateTime> sub_category_time_modified { get; set; }
        public string sub_category_icondir { get; set; }
        public int sub_category_agent_id { get; set; }
        public string map_tour { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual ICollection<agent_category_permission> agent_category_permission { get; set; }
        public virtual smt_parent_category smt_parent_category { get; set; }
        public virtual smt_user smt_user { get; set; }
    }
}
