//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smt_location
    {
        public smt_location()
        {
            this.smt_comment = new HashSet<smt_comment>();
            this.smt_user_history = new HashSet<smt_user_history>();
        }
    
        public long location_id { get; set; }
        public int sub_category_id { get; set; }
        public Nullable<double> location_latitude { get; set; }
        public Nullable<double> location_longitude { get; set; }
        public string location_name_vi { get; set; }
        public string location_name_en { get; set; }
        public string location_short_des_vi { get; set; }
        public string location_short_des_en { get; set; }
        public string location_des_vi { get; set; }
        public string location_des_en { get; set; }
        public string location_icondir { get; set; }
        public string location_videodir { get; set; }
        public Nullable<bool> location_shared { get; set; }
        public string location_addr_en { get; set; }
        public string location_addr { get; set; }
        public Nullable<int> location_user_created { get; set; }
        public Nullable<System.DateTime> location_time_created { get; set; }
        public Nullable<int> location_user_modified { get; set; }
        public Nullable<System.DateTime> location_time_modified { get; set; }
        public string location_contact_web { get; set; }
        public string location_contact_phone { get; set; }
        public int agent_id { get; set; }
        public sbyte location_state { get; set; }
        public Nullable<int> location_counter { get; set; }
        public Nullable<int> location_parent_id { get; set; }
        public Nullable<int> location_layer_id { get; set; }
        public string location_video_streaming { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual ICollection<smt_comment> smt_comment { get; set; }
        public virtual smt_layer smt_layer { get; set; }
        public virtual smt_user smt_user { get; set; }
        public virtual ICollection<smt_user_history> smt_user_history { get; set; }
    }
}
