//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smt_contact
    {
        public int contact_id { get; set; }
        public string contact_contain { get; set; }
        public string contact_contain_en { get; set; }
    }
}
