//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTourWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smt_link_tour
    {
        public int link_tour_id { get; set; }
        public string tour_des_en { get; set; }
        public string tour_des_vi { get; set; }
        public string tour_link { get; set; }
        public string tour_name { get; set; }
        public string tour_name_en { get; set; }
    }
}
